apiVersion: apps/v14frwf
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: myapp-argo-application
  name: myapp-deployment
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: myapp
          image: 'nanajanashia/argocd-app:1.0'
          ports:
            - containerPort: 8080

